server:
  servlet:
    context-path: /mobilityapi
  port: 8888
  error:
    include-message: always
spring:
    mvc:
      pathmatch:
            matching-strategy: ant_path_matcher
app:
  datasource:
     url:
       parkings-list: https://data.grandpoitiers.fr/api/records/1.0/search/?dataset=mobilite-parkings-grand-poitiers-donnees-metiers&rows=1000&facet=nom_du_parking&facet=zone_tarifaire&facet=statut2&facet=statut3
       available-slots: https://data.grandpoitiers.fr/api/records/1.0/search/?dataset=mobilites-stationnement-des-parkings-en-temps-reel&facet=nom
     
